name: "Close Pull Request to branch Dev"

on:
  push:
    branches:
      - dev

jobs:
  determine-actions:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

  # PROVISION CORE & PREVIEW INFRASTRUCTURE ----------------------------------------------------
  provision-infrastructure:
    needs: determine-actions
    uses: "./.github/workflows/rw-provision-infrastructure.yml"
    permissions:
      contents: read
      id-token: write
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_administrator_login: ${{ secrets.TF_VAR_ADMINISTRATOR_LOGIN }}
      TF_VAR_administrator_password: ${{ secrets.TF_VAR_ADMINISTRATOR_PASSWORD }}
    with:
      TF_VAR_prefix: ${{ vars.TF_VAR_PREFIX }}
      TF_VAR_location: ${{ vars.TF_VAR_LOCATION }}
      run-core: true
      run-preview: false
      destroy-preview: true

  # FRONTEND ------------------------------------------------------------------------------------
  frontend:
    needs: [provision-infrastructure, determine-actions]
    if: needs.determine-actions.outputs.frontend == 'true'
    uses: "./.github/workflows/rw-all-in-one.yml"
    permissions:
      contents: read
      id-token: write
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    with:
      acr: ${{ vars.TF_VAR_PREFIX }}acr
      cluster-name: ${{ vars.TF_VAR_PREFIX }}aks
      resource-group-name: ${{ vars.TF_VAR_PREFIX }}rg
      project: frontend
      namespace: dev
  
# BACKEND ------------------------------------------------------------------------------------
  backend:
    needs: [provision-infrastructure, determine-actions]
    if: needs.determine-actions.outputs.backend == 'true'
    uses: "./.github/workflows/rw-all-in-one.yml"
    permissions:
      contents: read
      id-token: write
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    with:
      acr: ${{ vars.TF_VAR_PREFIX }}acr
      cluster-name: ${{ vars.TF_VAR_PREFIX }}aks
      resource-group-name: ${{ vars.TF_VAR_PREFIX }}rg
      project: backend
      namespace: dev