name: "rw-build"

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build and Test React app
        run: |
          npm install
          npm run build
          npm test
        working-directory: ${{ github.workspace }}/${{ inputs.project }}
