name: "rw-deploy"

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
    inputs:
      resource-group-name:
        required: true
        type: string
      acr:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      project:
        required: true
        type: string
      
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure CLI login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Update kube-config
        run: az aks get-credentials --resource-group "${{ inputs.resource-group-name }}" --name "${{ inputs.cluster-name }}"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Apply Helm chart
        run: helm upgrade --install ${{ inputs.project }} . --set image.tag="${{ github.event.number }}" --set image.repository="${{ inputs.acr }}/${{ inputs.project }}"
        working-directory: ${{ github.workspace }}/infrastructure/helm-chart/${{ inputs.project }}
 