name: "rw-provision-infrastructure"

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      TF_VAR_administrator_login:
        required: true
      TF_VAR_administrator_password:
        required: true

    inputs:
      TF_VAR_prefix:
        required: true
        type: string
      TF_VAR_location:
        required: true
        type: string
      run-preview:
        required: true
        type: boolean

jobs:

  core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure CLI login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_wrapper: false
      - name: Provision Core infrastructure
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_prefix: ${{ inputs.TF_VAR_PREFIX }}
          TF_VAR_location: ${{ inputs.TF_VAR_LOCATION }}
          TF_VAR_administrator_login: ${{ secrets.TF_VAR_ADMINISTRATOR_LOGIN }}
          TF_VAR_administrator_password: ${{ secrets.TF_VAR_ADMINISTRATOR_PASSWORD }}
        run: |
          terraform init --backend-config="key=core.tfstate"
          terraform plan
          terraform apply --auto-approve
        working-directory: ${{ github.workspace }}/infrastructure/terraform/core

  preview:
    needs: core
    runs-on: ubuntu-latest
    if: ${{ inputs.run-preview == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure CLI login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_wrapper: false
      - name: Provision Preview infrastructure
        if: ${{ inputs.run-preview == 'true' }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_prefix: ${{ inputs.TF_VAR_PREFIX }}
          TF_VAR_location: ${{ inputs.TF_VAR_LOCATION }}
        run: |
          terraform init --backend-config="key=preview-${{ github.event.id }}.tfstate"
          terraform plan
          terraform apply --auto-approve
        working-directory: ${{ github.workspace }}/infrastructure/terraform/preview
      - name: Update kube-config
        run: az aks get-credentials --resource-group "${{ inputs.TF_VAR_prefix }}rg" --name "${{inputs.TF_VAR_prefix}}aks" --overwrite-existing
      - name: Create preview namespace
        run: kubectl create namespace preview-${{ github.event.id }}