name: "rw-release"

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
    inputs:
      project:
        required: true
        type: string
      acr:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure CLI login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Login to ACR
        run: az acr login --name "${{ inputs.acr }}"
      - name: Build and push Docker image
        run: |
          docker build -t "${{ inputs.acr }}/${{ inputs.project }}:${{ github.event.number }}" .
          docker push "${{ inputs.acr }}/${{ inputs.project }}:${{ github.event.number }}"
        working-directory: ${{ github.workspace }}/${{ inputs.project }}